/**
 * Compact local blocklist of commonly breached passwords (HIPAA §1.1).
 * Normalized to lowercase alphanumeric for comparison.
 */
const COMMON_BREACHED_PASSWORDS = new Set(
  [
    'password',
    'password1',
    'password123',
    'password123!',
    '123456',
    '12345678',
    '123456789',
    '1234567890',
    'qwerty',
    'qwerty123',
    'abc123',
    'abcdef',
    'letmein',
    'welcome',
    'welcome1',
    'admin',
    'admin123',
    'administrator',
    'iloveyou',
    'monkey',
    'dragon',
    'master',
    'login',
    'princess',
    'football',
    'baseball',
    'soccer',
    'hockey',
    'mustang',
    'shadow',
    'sunshine',
    'trustno1',
    'passw0rd',
    'p@ssw0rd',
    'p@ssword',
    'pass@word1',
    'changeme',
    'secret',
    'root',
    'toor',
    'guest',
    'default',
    'test',
    'test123',
    'testing',
    'user',
    'user123',
    'username',
    'access',
    'hello',
    'hello123',
    'freedom',
    'whatever',
    'qazwsx',
    'zxcvbn',
    'zxcvbnm',
    '1q2w3e4r',
    '1qaz2wsx',
    'qwertyuiop',
    'asdfghjkl',
    'zaq12wsx',
    'starwars',
    'batman',
    'superman',
    'michael',
    'jennifer',
    'hunter',
    'buster',
    'soccer1',
    'charlie',
    'aa123456',
    'password!',
    'Password1',
    'Password1!',
    'Password123',
    'Password123!',
    'Welcome1',
    'Welcome123',
    'Welcome1!',
    'Summer2024',
    'Summer2025',
    'Winter2024',
    'Winter2025',
    'Spring2024',
    'Spring2025',
    'Fall2024',
    'Fall2025',
    'Healthcare1',
    'Healthcare1!',
    'Universal1',
    'Universal1!',
    'TempPass1!',
    'TempPassword1',
  ].map(value => value.toLowerCase())
)

export function isCommonBreachedPassword(password: string): boolean {
  const normalized = password.trim().toLowerCase()
  if (!normalized) return false
  if (COMMON_BREACHED_PASSWORDS.has(normalized)) return true

  // Strip common separators and re-check
  const compact = normalized.replace(/[^a-z0-9]/g, '')
  return COMMON_BREACHED_PASSWORDS.has(compact)
}
