-- AlterTable
ALTER TABLE "Medication" ADD COLUMN IF NOT EXISTS "timesPerDay" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Medication" ADD COLUMN IF NOT EXISTS "timesOfDay" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
